# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qOa_UOfP42uTVFdUbd2FrZebdsZZ4EXG

TRABAJOS PRÄCTICOS
"""

#ejercicio 1
print ("resolviendo el ejercicio 1")